const componentsRoutes = {
  ",/": "Dashboard",
  "/components": "Components",
  "/charts": "Charts",
  "/components/buttons": "Buttons",
  "/components/social-buttons": "Social Buttons",
  "/components/cards": "Cards",
  "/components/forms": "Forms",
  "/components/modals": "Modals",
  "/components/switches": "Switches",
  "/components/tables": "Tables",
  "/icons": "Icons",
  "/icons/font-awesome": "Font Awesome",
  "/icons/simple-line-icons": "Simple Line Icons",
  "/widgets": "Widgets",
  "/logout": "Logout",
  "/consultant": "Consultant",
  "/consultant/info": "Info",
  "/consultant/podetails": "podetails",
  "/consultant/rfs": "rfs",
  "/consultant/rr": "rr",
  "/consultant/onoffboard": "onoffboard",
  "/consultant/workpremit": "workpremit"
};
export default componentsRoutes;
